# Generated by Django 4.1.5 on 2023-01-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.SmallIntegerField(),
        ),
    ]
