# Generated by Django 4.1.5 on 2023-01-06 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_person_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
    ]
