# Generated by Django 4.1.5 on 2023-01-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_person_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.SmallIntegerField(default=1),
        ),
    ]
