# Generated by Django 4.1.7 on 2023-03-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_car_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='market_segment',
            field=models.CharField(choices=[('A', 'mini car'), ('B', 'small car'), ('C', 'medium car'), ('D', 'large car'), ('F', 'luxury car'), ('S', 'sport car')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(default='Best ever car'),
        ),
    ]
