# Generated by Django 4.1.7 on 2023-03-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_message_alter_car_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='datetime_sent',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
