# Generated by Django 4.1.5 on 2023-01-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_literaryformat_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literaryformat',
            name='format',
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
