# Generated by Django 4.1.7 on 2023-03-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_car_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
