# Generated by Django 4.1.5 on 2023-01-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_message_alter_book_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='datetime_field',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
