# Generated by Django 4.1.7 on 2023-03-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_car_market_segment_alter_car_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('datetime_sent', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='creation_date',
            field=models.DateField(blank=True, null=True, verbose_name="Use description when it's really necessary"),
        ),
    ]
