# Generated by Django 4.1.7 on 2023-03-07 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='db.literaryformat'),
        ),
    ]
