# Generated by Django 4.1.7 on 2023-03-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(null=True, upload_to="books/"),
        ),
    ]
