# Generated by Django 4.1.7 on 2023-04-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("station", "0002_alter_bus_facilities"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bus",
            name="facilities",
        ),
        migrations.AddField(
            model_name="bus",
            name="facilities",
            field=models.ManyToManyField(null=True, to="station.facility"),
        ),
    ]
