# Generated by Django 4.1.7 on 2023-04-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("station", "0003_remove_bus_facilities_bus_facilities"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"default_related_name": "orders", "ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={"default_related_name": "tickets"},
        ),
        migrations.AlterField(
            model_name="bus",
            name="facilities",
            field=models.ManyToManyField(to="station.facility"),
        ),
    ]
