# Generated by Django 4.1.7 on 2023-04-09 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("station", "0004_alter_order_options_alter_ticket_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"default_related_name": "tickets", "ordering": ("seat",)},
        ),
    ]
