# Generated by Django 4.1.7 on 2023-04-10 10:47

from django.db import migrations, models
import station.models


class Migration(migrations.Migration):
    dependencies = [
        ("station", "0005_alter_ticket_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="image",
            field=models.ImageField(
                null=True, upload_to=station.models.bus_image_file_path
            ),
        ),
    ]
