# Generated by Django 4.1.7 on 2023-03-14 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bus',
            table='bus',
        ),
    ]
