# Generated by Django 4.1.7 on 2023-03-14 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_bus_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name_plural': 'buses'},
        ),
        migrations.AlterModelTable(
            name='bus',
            table=None,
        ),
    ]
