# Generated by Django 4.1.7 on 2023-03-14 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_bus_options_alter_bus_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
