# Generated by Django 4.1.7 on 2023-03-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_order_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['source', 'destination'], name='db_trip_source_ba31b6_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['departure'], name='db_trip_departu_5ae30a_idx'),
        ),
    ]
