# Generated by Django 4.1.5 on 2023-01-11 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persons',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Genders',
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
        migrations.DeleteModel(
            name='Persons',
        ),
    ]
