# Generated by Django 4.1.7 on 2023-03-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('horse_power', models.IntegerField()),
                ('creation_date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
