# Generated by Django 4.1.7 on 2023-03-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='creation_date',
            field=models.DateField(null=True),
        ),
    ]
