# Generated by Django 4.1.7 on 2023-03-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_car_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='market_segment',
            field=models.CharField(choices=[('S', 'Small car'), ('M', 'Medium car'), ('L', 'Large car')], default='M', max_length=1),
        ),
    ]
