# Generated by Django 4.1.7 on 2023-03-10 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_car_market_segment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='literaryformat',
            name='format',
            field=models.CharField(max_length=63),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('authors', models.ManyToManyField(related_name='books', to='db.author')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='db.literaryformat')),
            ],
        ),
    ]
