# Generated by Django 4.1.7 on 2023-03-10 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_author_alter_literaryformat_format_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.AlterField(
            model_name='book',
            name='format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.literaryformat'),
        ),
    ]
