# Generated by Django 4.1.5 on 2023-01-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_field', models.DateTimeField(auto_created=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1, verbose_name='Just description'),
        ),
    ]
